# Generated by Django 5.1 on 2024-12-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='envio',
            fields=[
                ('id_envio', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('id_cliente', models.CharField(max_length=6)),
                ('id_empleado', models.CharField(max_length=6)),
                ('id_producto', models.CharField(max_length=100)),
                ('fecha_pedido', models.DateField()),
                ('cantidad_productos', models.CharField(max_length=50)),
                ('total', models.CharField(max_length=15)),
            ],
        ),
    ]
