# Generated by Django 5.1 on 2024-12-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='local',
            fields=[
                ('id_local', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=50)),
                ('gerente', models.CharField(max_length=100)),
                ('empleados', models.CharField(max_length=15)),
                ('cantidad_productos', models.CharField(max_length=50)),
                ('num_telefono', models.CharField(max_length=15)),
            ],
        ),
    ]
