# Generated by Django 5.1 on 2024-12-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores_app', '0003_alter_proveedores_id_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedores',
            name='id_proveedor',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
