# Generated by Django 5.1 on 2024-12-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empleados',
            fields=[
                ('id_empleado', models.IntegerField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=50)),
                ('num_telefono', models.IntegerField(max_length=15)),
                ('fecha_nacimiento', models.DateField(verbose_name='')),
                ('fecha_ingreso', models.DateField(verbose_name='')),
                ('puesto', models.CharField(max_length=50)),
                ('salario', models.IntegerField(max_length=50)),
            ],
        ),
    ]
