# Generated by Django 5.1 on 2024-12-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados_app', '0002_alter_empleados_fecha_ingreso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='id_empleado',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='num_telefono',
            field=models.IntegerField(),
        ),
    ]
